server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RewritePath=/(?<segment>.*), /api/v1/$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: user-service
          uri: http://localhost:9091
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/user
        - id: rent-service
          uri: http://localhost:9093
          predicates:
            - Path=/rent/**
          filters:
            - name: CircuitBreaker
              args:
                name: rentCircuitBreaker
                fallbackUri: forward:/fallback/rent

        - id: car-service
          uri: http://localhost:9093
          predicates:
            - Path=/car/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartCircuitBreaker
                fallbackUri: forward:/fallback/car



